export const bloodBanksData = [
  {
    id: 1,
    name: "Red Cross Blood Bank",
    city: "Madanapalle",
    address: "123 Life St, Madanapalle",
    open: "9 AM - 5 PM",
    services: ["Whole Blood", "Platelets"],
    lat: 13.6333, 
    lon: 78.5,
  },
  {
    id: 2,
    name: "LifeSaver Hospital",
    city: "Anantapur",
    address: "456 Health Ave, Anantapur",
    open: "24 Hours",
    services: ["Whole Blood", "Plasma"],
    lat: 14.6819,
    lon: 77.6006,
  },
  {
    id: 3,
    name: "Community Blood Center",
    city: "Chittoor",
    address: "789 Tech Park Rd, Chittoor",
    open: "8 AM - 8 PM",
    services: ["Whole Blood", "Platelets", "Plasma"],
    lat: 13.2167,
    lon: 79.1167,
  },
  {
    id: 4,
    name: "Reddrop Clinic",
    city: "Tirupati",
    address: "101 Marine Dr, Tirupati",
    open: "10 AM - 6 PM",
    services: ["Whole Blood"],
    lat: 13.65,
    lon: 79.4167,
  },
  {
    id: 5,
    name: "Jeevan Dhara Blood Bank",
    city: "Kadapa",
    address: "202 Main Rd, Kadapa",
    open: "9 AM - 7 PM",
    services: ["Whole Blood", "Platelets"],
    lat: 14.4667,
    lon: 78.8167,
  },
  {
    id: 6,
    name: "Rakthdaan Kendra",
    city: "Kurnool",
    address: "303 Bypass Rd, Kurnool",
    open: "8 AM - 6 PM",
    services: ["Whole Blood", "Plasma"],
    lat: 15.8281,
    lon: 78.0374,
  },
];

